# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f92e5e75b164036b9afeacf5342f22c185ddfb273050af7567a12fc9fb49bfe4e3a86a8a328b3f3be1f4693c117babb724bdfbba52a718f978983a7a4ff1055f

test:
  secret_key_base: fa8855bb2af2b4055030d1e1ec7769c4dddab63e79bc85c3d3b29bd0af41d2b0da9178e19bec67a1f38cd29e487c473ecfbc8107c94a48a58270c235d51c4c61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
